version: '3'
services:
  api:
    build: ./api
    command: sh run_api.sh
    volumes:
      - ./api:/app
      - rails-tmp:/api/tmp
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ceki
      - POSTGRES_PASSWORD=seproject7
      - POSTGRES_DB=ceki_dev
  front:
    build: ./front
    command: npm run nuxt
    volumes:
      - ./front:/app
      - node-modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - API_URL_BROWSER=/api
      - API_URL=http://api:3000/
  nginx:
    image: nginx
    depends_on:
      - api
      - front
    ports:
      - "8888:80"
    volumes:
      - ./cekilib.dev.conf:/etc/nginx/conf.d/default.conf
      - ./front:/mnt/front
      - ./api/public/uploads:/uploads
      - ./api/public/not_found.png:/not_found.png
volumes:
  pg-data:
  node-modules:
  rails-tmp:
