version: '3'
services:
  api:
    build: ./api
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ./api:/app
      - rails-tmp:/api/tmp
    depends_on:
      - postgres
  postgres:
    image: postgres:9.4
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ceki
      - POSTGRES_PASSWORD=seproject7
      - POSTGRES_DB=ceki_dev
  front:
    build: ./front
    command: npm run dev
    volumes:
      - ./front:/app
      - node-modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
  nginx:
    image: nginx
    depends_on:
      - api
      - front
    ports:
      - "8888:80"
    volumes:
      - ./cekilib.dev.conf:/etc/nginx/conf.d/default.conf
      - ./front:/mnt/front
volumes:
  pg-data:
  node-modules:
  rails-tmp:

